export enum MutationTypes {
  SET_SHOW_REQUEST_MODAL = 'SET_SHOW_REQUEST_MODAL',
  SET_CURRENT_REQUEST = 'SET_CURRENT_REQUEST',
  SET_INFO_CODE = 'SET_INFO_CODE',
  SET_ERROR_CODE = 'SET_ERROR_CODE',
}
