export enum ActionTypes {
  ADD_RECIPIENT = 'ADD_RECIPIENT',
  UPDATE_RECIPIENT = 'UPDATE_RECIPIENT',
  REMOVE_RECIPIENT = 'REMOVE_RECIPIENT',
  FORWARD_REQUEST = 'FORWARD_REQUEST',
  FORWARD_REQUEST_TO_RECIPIENT = 'FORWARD_REQUEST_TO_RECIPIENT',
  UPDATE_REQUEST = 'UPDATE_REQUEST',
  SHOW_REQUEST = 'SHOW_REQUEST',
  HIDE_REQUEST = 'HIDE_REQUEST',
}
