export enum MutationTypes {
  SET_REQUESTS = 'SET_REQUESTS',
  SET_IS_BOOTED = 'SET_IS_BOOTED',
  SET_LOADING = 'SET_LOADING',
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
  SET_PER_PAGE = 'SET_PER_PAGE',
  SET_TOTAL_ROWS = 'SET_TOTAL_ROWS',
  SET_ERROR_CODE = 'SET_ERROR_CODE',
}
